name: Node.js Package
on:
  push:
    branches:
      - main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/
      - name: Publish to npm
        run: npm publish || echo "版本可能已存在，跳过发布"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
